// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// 
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD5e6-JVj_32O8QG8URscBV5epeQ9Z8pGU',
//     appId: '1:890474310680:web:9a3748bf314ffdcb76276d',
//     messagingSenderId: '890474310680',
//     projectId: 'kindmeals-fba5e',
//     authDomain: 'kindmeals-fba5e.firebaseapp.com',
//     storageBucket: 'kindmeals-fba5e.firebasestorage.app',
//     measurementId: 'G-DXRFNJ1MQ0',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBObmkl9FM6dH3y9YKO2xIIme98NXptHLY',
//     appId: '1:890474310680:android:be2236633d61261f76276d',
//     messagingSenderId: '890474310680',
//     projectId: 'kindmeals-fba5e',
//     storageBucket: 'kindmeals-fba5e.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBRKEmDpXdxM_kD4mZrbL2NNz1hP8p66wY',
//     appId: '1:890474310680:ios:e4f0ef14c44710d576276d',
//     messagingSenderId: '890474310680',
//     projectId: 'kindmeals-fba5e',
//     storageBucket: 'kindmeals-fba5e.firebasestorage.app',
//     androidClientId: '890474310680-9h9ek0vv3601q4gi9065m8aph4chp7b8.apps.googleusercontent.com',
//     iosClientId: '890474310680-58p8j81j8eso2ricjv8e3oqavgugl14s.apps.googleusercontent.com',
//     iosBundleId: 'com.example.kindmeals',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBRKEmDpXdxM_kD4mZrbL2NNz1hP8p66wY',
//     appId: '1:890474310680:ios:e4f0ef14c44710d576276d',
//     messagingSenderId: '890474310680',
//     projectId: 'kindmeals-fba5e',
//     storageBucket: 'kindmeals-fba5e.firebasestorage.app',
//     androidClientId: '890474310680-9h9ek0vv3601q4gi9065m8aph4chp7b8.apps.googleusercontent.com',
//     iosClientId: '890474310680-58p8j81j8eso2ricjv8e3oqavgugl14s.apps.googleusercontent.com',
//     iosBundleId: 'com.example.kindmeals',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD5e6-JVj_32O8QG8URscBV5epeQ9Z8pGU',
//     appId: '1:890474310680:web:26f882f84bf2605676276d',
//     messagingSenderId: '890474310680',
//     projectId: 'kindmeals-fba5e',
//     authDomain: 'kindmeals-fba5e.firebaseapp.com',
//     storageBucket: 'kindmeals-fba5e.firebasestorage.app',
//     measurementId: 'G-JWT67CEDG5',
//   );
// }


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'No web configuration provided. Add web support in Firebase console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'No iOS configuration provided. Add iOS support in Firebase console.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'No macOS configuration provided. Add macOS support in Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'No Windows configuration provided. Add Windows support in Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'No Linux configuration provided. Add Linux support in Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5ZEm_xRYLVA-9GNO7KVs8Ctrx0C0VvI',
    appId: '1:656754915837:android:ddcb83bfaee7682ec30194',
    messagingSenderId: '656754915837',
    projectId: 'kindmeals-5c993',
    storageBucket: 'kindmeals-5c993.firebasestorage.app',
  );
}